### PR TITLE
#3 API to SignIn

### LINKED ISSUE #3: UserController: API to Sign-in
**signin - "/user/signin"**

This endpoint is used for user authentication. The user authenticates in the application and after successful authentication, JWT token is given to a user.

- It should be a POST request

- This endpoint requests for the User credentials to be passed in the authorization field of header as part of Basic authentication. You need to pass "Basic username:password" (where username:password of the String is encoded to Base64 format) in the authorization header.

- If the username provided by the user does not exist, throw "AuthenticationFailedException" with the message code -'ATH-001' and message-'This username does not exist'.

- If the password provided by the user does not match the password in the existing database, throw 'AuthenticationFailedException' with the message code -'ATH-002' and message -'Password failed'.

- If the credentials provided by the user match the details in the database, save the user login information in the database and return the 'uuid' of the authenticated user from 'users' table and message 'SIGNED IN SUCCESSFULLY' in the JSON response with the corresponding HTTP status. Note that 'JwtAccessToken' class has been given in the stub file to generate an access token.

- Also, return the access token in the access_token field of the Response Header, which will be used by the user for any further operation in the Quora Application.
- Read more @https://learn.upgrad.com/v/course/867/session/140118/segment/759581

### PR DESCRIPTION
**Pull request by Piyasi-lab**
SignIn API created

### CODE REVIEW

File: quora-api/src/main/java/com/upgrad/quora/api/exception/RestExceptionHandler.java [hunk 1]
```diff
@@ -22,4 +23,17 @@
...
+
+    /**
+     * This method handles the exception for failed Authentication
+     * @param exe
+     * @param request
+     * @return
+     */
+    @ExceptionHandler(AuthenticationFailedException.class)
+    public ResponseEntity<ErrorResponse> signinException(AuthenticationFailedException exe, WebRequest request) {
+        return new ResponseEntity<ErrorResponse>(
```
Comment (soniyakocher) [inline quora-api/src/main/java/com/upgrad/quora/api/exception/RestExceptionHandler.java:36]: The more correct Http status should be UNAUTHORIZED

File: quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java [hunk 2]
```diff
@@ -51,4 +58,28 @@
...
+
+    /**
+     * Method to signIn the application
+     * @param authorization
+     * @return
+     * @throws AuthenticationFailedException
+     */
+    @RequestMapping(method = RequestMethod.POST, path = "/user/signin", produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
+    public ResponseEntity<SigninResponse> login(@RequestHeader("authorization") final String authorization) throws AuthenticationFailedException {
+        byte[] decode = Base64.getDecoder().decode(authorization);
```
Comment (soniyakocher) [inline quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java]: we are require to use Basic authentication so "Basic username :Password" U didn't include "Basic" in ur authentication

File: quora-service/src/main/java/com/upgrad/quora/service/entity/UserAuthTokenEntity.java [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+    @Column(name = "ID")
+    @GeneratedValue(strategy = GenerationType.IDENTITY)
+    private long id;
+
+    @ManyToOne
+    @JoinColumn(name = "USER_ID")
+    private UserEntity user;
+
+    @Column(name = "UUID")
+    @Size(max = 200)
```
Comment (soniyakocher) [inline quora-service/src/main/java/com/upgrad/quora/service/entity/UserAuthTokenEntity.java:32]: use @NOTNULL annotation for uuid as it is mention in quora.sql class

File: quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java [hunk 4]
```diff
@@ -49,16 +50,17 @@
...
     @Column(name = "PASSWORD")
     @Size(max = 255)
     @NotNull
-    @ToStringExclude
     private String password;
 
     @Column(name = "SALT")
     @Size(max = 200)
     @NotNull
-    @ToStringExclude
```
Comment (soniyakocher) [inline quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java:61]: why we can't use @ToStringExclude ?

**Review by soniyakocher — CHANGES_REQUESTED** [review]
Suggested some changes rest all looks good to me.

File: quora-api/src/main/java/com/upgrad/quora/api/exception/RestExceptionHandler.java (hunk 1 above)
Comment (Piyasi-lab) [reply quora-api/src/main/java/com/upgrad/quora/api/exception/RestExceptionHandler.java:36]: Changes made.

File: quora-service/src/main/java/com/upgrad/quora/service/entity/UserAuthTokenEntity.java (hunk 3 above)
Comment (Piyasi-lab) [reply quora-service/src/main/java/com/upgrad/quora/service/entity/UserAuthTokenEntity.java:32]: Changes made.

File: quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java (hunk 2 above)
Comment (Piyasi-lab) [reply quora-api/src/main/java/com/upgrad/quora/api/controller/UserController.java]: Changes made.

File: quora-service/src/main/java/com/upgrad/quora/service/business/PasswordCryptographyProvider.java [hunk 5]
```diff
@@ -27,7 +27,7 @@
      * @param password char array.
      * @return String array with [0] encoded salt [1] hashed password.
      */
-    public String[] encrypt(final String password) {
+    public static String[] encrypt(final String password) {
```
Comment (cushivas) [inline quora-service/src/main/java/com/upgrad/quora/service/business/PasswordCryptographyProvider.java:30]: Any reason behind changing this to static ?

File: quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java [hunk 6]
```diff
@@ -1,6 +1,7 @@
 package com.upgrad.quora.service.dao;
 
-import com.upgrad.quora.service.entity.UserAuthEntity;
+//import com.upgrad.quora.service.entity.UserAuthEntity;
```
Comment (cushivas) [inline quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java]: rather than commenting an import, i would say remove it.

File: quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java [hunk 7]
```diff
@@ -49,16 +50,17 @@
     @Size(max = 50)
     private String email;
 
+    //@Column(name = "LAST_LOGIN_AT")
```
Comment (cushivas) [inline quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java]: If unused, please remove

**Review by cushivas — CHANGES_REQUESTED** [review]
Comments Inside

File: quora-service/src/main/java/com/upgrad/quora/service/business/AuthenticationService.java [hunk 8]
```diff
@@ -60,4 +62,23 @@ public UserAuthTokenEntity authenticate(final String username, final String pass
...
+     */
+    @Transactional(propagation = Propagation.REQUIRED)
+    public String deleteToken(final String authorizationToken) throws SignOutRestrictedException {
+        //Check if the user is not logged in
+        UserAuthTokenEntity userAuthTokenEntity = userDao.getUserAuthToken(authorizationToken);
+        if (userAuthTokenEntity == null) {
+            throw new SignOutRestrictedException("SGR-001", "User is not Signed in");
+        }
+        String uuid = userAuthTokenEntity.getUuid();
+        userDao.deleteAuthToken(userAuthTokenEntity);
```
Comment (soniyakocher) [inline quora-service/src/main/java/com/upgrad/quora/service/business/AuthenticationService.java]: The method says that if the token is valid we need to update logoutAt time   which i didn't see in the code above can u plz explain? and also why deleteAuthtoken ?

File: quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java [hunk 9]
```diff
@@ -76,4 +89,8 @@ public UserAuthTokenEntity createAuthToken(final UserAuthTokenEntity userAuthTok
     public void updateUser(final UserEntity updatedUserEntity) {
         entityManager.merge(updatedUserEntity);
     }
+
+    public void deleteAuthToken(final UserAuthTokenEntity deleteAuthToken){
```
Comment (soniyakocher) [inline quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java]: we need to update auth token then y updating user the parameter should be UserAuthEntity type?

**Review by soniyakocher — APPROVED** [review]

File: quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java (hunk 4 above)
Comment (Piyasi-lab) [reply quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java:61]: There were compilation issues. This annotation does not exists.

File: quora-service/src/main/java/com/upgrad/quora/service/business/PasswordCryptographyProvider.java (hunk 5 above)
Comment (Piyasi-lab) [reply quora-service/src/main/java/com/upgrad/quora/service/business/PasswordCryptographyProvider.java:30]: There were compilation issues because we have called this method without creating object of the class.

File: quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java (hunk 9 above)
Comment (Piyasi-lab) [reply quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java]: Done.

File: quora-service/src/main/java/com/upgrad/quora/service/business/AuthenticationService.java (hunk 8 above)
Comment (Piyasi-lab) [reply quora-service/src/main/java/com/upgrad/quora/service/business/AuthenticationService.java]: Changed.

File: quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java (hunk 6 above)
Comment (Piyasi-lab) [reply quora-service/src/main/java/com/upgrad/quora/service/dao/UserDao.java]: Done.

File: quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java (hunk 7 above)
Comment (Piyasi-lab) [reply quora-service/src/main/java/com/upgrad/quora/service/entity/UserEntity.java]: Done.

File: quora-service/src/main/java/com/upgrad/quora/service/business/PasswordCryptographyProvider.java (hunk 5 above)
Comment (cushivas) [reply quora-service/src/main/java/com/upgrad/quora/service/business/PasswordCryptographyProvider.java:30]: ok

File: quora-service/src/main/java/com/upgrad/quora/service/business/AuthenticationService.java (hunk 8 above)
Comment (cushivas) [reply quora-service/src/main/java/com/upgrad/quora/service/business/AuthenticationService.java]: If the access token provided by the user is valid, update the LogoutAt time of the user in the database and return the 'uuid' of the signed out user from 'users' table and message 'SIGNED OUT SUCCESSFULLY' in the JSON response with the corresponding HTTP status.

Please address this requirement

**Review by cushivas — CHANGES_REQUESTED** [review]

**Review by cushivas — APPROVED** [review]
Looks good.
